apiVersion: apps/v1
kind: Deployment
metadata:
  name: wdym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wdym
  template:
    metadata:
      labels:
        app: wdym
    spec:
      containers:
      - image: okteto.dev/wdym:latest
        name: wdym
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f8bfb621-6728-4a6c-ae69-2106cd3d7c8a"
        - name: Vless_Path
          value: "/vless"
        - name: Vmess_UUID
          value: "f8bfb621-6728-4a6c-ae69-2106cd3d7c8a"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "/v2link"
